create table if not exists public.precios (
    id bigint generated by default as identity primary key,
    supermercado text not null,
    nombre_producto text not null,
    precio numeric not null,
    unidad text,
    fecha_registro date not null,
    categoria text,
    url_producto text,
    moneda text default 'PYG',
    fecha_hora_registro timestamptz,
    created_at timestamptz not null default now(),
    constraint precios_unico_producto_fecha unique (
        supermercado,
        nombre_producto,
        fecha_registro
    )
);

alter table public.precios
add column if not exists categoria text;

alter table public.precios
add column if not exists url_producto text;

alter table public.precios
add column if not exists moneda text default 'PYG';

alter table public.precios
add column if not exists fecha_hora_registro timestamptz;

alter table public.precios
add column if not exists created_at timestamptz not null default now();

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'precios_unico_producto_fecha'
    ) then
        alter table public.precios
        add constraint precios_unico_producto_fecha unique (
            supermercado,
            nombre_producto,
            fecha_registro
        );
    end if;
end $$;

create index if not exists idx_precios_fecha
on public.precios (fecha_registro);

create index if not exists idx_precios_producto
on public.precios (nombre_producto);

create index if not exists idx_precios_supermercado
on public.precios (supermercado);
